# Generated by Django 4.2.7 on 2025-11-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='Anonymous', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_pages/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.IntegerField()),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='api.blogpost')),
            ],
            options={
                'verbose_name': 'Paragraph',
                'verbose_name_plural': 'Paragraphs',
                'ordering': ['paragraph_id'],
                'unique_together': {('post', 'paragraph_id')},
            },
        ),
        migrations.CreateModel(
            name='Underline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The underlined text')),
                ('start_offset', models.IntegerField(help_text='Starting position in paragraph text')),
                ('end_offset', models.IntegerField(help_text='Ending position in paragraph text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlines', to='api.paragraph')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlines', to='api.blogpost')),
            ],
            options={
                'verbose_name': 'Underline',
                'verbose_name_plural': 'Underlines',
                'ordering': ['start_offset'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The specific text highlighted/underlined')),
                ('note', models.TextField(help_text="User's thought or commentary")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='api.paragraph')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='api.blogpost')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['-created_at'],
            },
        ),
    ]
